poke: 2_worldMapRunner.c 1_mapWorldGeneration.c 3_heapDijkstra.c 5_pokeNcurses.c
	gcc 2_worldMapRunner.c 1_mapWorldGeneration.c 3_heapDijkstra.c 5_pokeNcurses.c -lncurses -o poke

clean:
	rm -f *.o poke poke.exe
