poke: 0_start.cpp 0_printing.cpp 1_mapWorldGeneration.cpp 2_worldMapRunner.cpp 3_heapDijkstra.cpp 4_characters.cpp 5_ncurses.cpp 6_playerTileTraversal.cpp 7_pokedex.cpp
	g++ 0_start.cpp 0_printing.cpp 1_mapWorldGeneration.cpp 2_worldMapRunner.cpp 3_heapDijkstra.cpp 4_characters.cpp 5_ncurses.cpp 6_playerTileTraversal.cpp 7_pokedex.cpp -lncurses -o poke

clean:
	rm -f *.o poke poke.exe
